- package.json
> Deploy to Azure

- package.json
- yarn.lock
> force react/gatsby version for now

- design.js
- src/pages/design/index.md
- src/pages/design/ux-patterns/Designingforphotoshop.md
- src/pages/design/ux-patterns/branding.md
- src/pages/design/ux-patterns/index.md
- src/pages/design/ux-patterns/messaging.md
> Design updates from Daniela

- gatsby-config.js
- reference-design.js
- src/pages/design/user-interface/index.md
- src/pages/design/ux-patterns/Designingforphotoshop.md
- src/pages/design/ux-patterns/index.md
> Updates from @dcaiced0

- gatsby-config.js
- src/pages/uxp/known-issues.md
> add known issues

- package.json
> Update version & pin

- package.json
> Push stage & prod again

- src/pages/ps_reference/classes/action.md
- src/pages/ps_reference/classes/actionset.md
- src/pages/ps_reference/classes/document.md
- src/pages/ps_reference/classes/grouplayer.md
- src/pages/ps_reference/classes/layer.md
- src/pages/ps_reference/classes/photoshop.md
- src/pages/ps_reference/classes/selection.md
- src/pages/ps_reference/interfaces/transformable.md
> make all links in ps_reference absolute

- src/pages/code_samples/batchplay_samples/index.md
- src/pages/code_samples/react_samples/index.md
- src/pages/guides/uxp-developer-tool/index.md
Fixed a 404 on page /guides/uxp-developer-tool/index.md
> Chuck max01

- package.json
> Last push around keynote

- src/pages/guides/uxp_guide/uxp-toolchain/index.md
> Fixing yarn ref, removing UXP CLI ref

- package.json
> Fix CLI mention & yarn link (#75 from @chuckweger)

- src/pages/design/index.md
> Update from @dcaiced0

- package.json
> Fix from @dcaiced0 for design 404s

- README.md
Update README.md to include authoring and deployment process.
See README.md for changes.
Fixes #77 
Indicates to authors and readers how our deployment process works, and the typical process.
No; just a README.md update.
- README Update
> Deployment process (Fixes #77)

- package-lock.json
- reference-css.js
- reference-html.js
- reference-js.js
- reference-spectrum.js
- src/pages/design/index.md
- src/pages/design/ux-patterns/index.md
- src/pages/design/ux-patterns/messaging.md
- src/pages/design/ux-patterns/onboarding.md
- src/pages/guides/uxp_for_you/uxp_for_newbies/index.md
- src/pages/guides/uxp_for_you/uxp_for_web_devs/index.md
- src/pages/guides/uxp_guide/uxp-misc/manifest-v4/index.md
- src/pages/guides/uxp_guide/uxp-misc/plugin-icons/index.md
- src/pages/ps_reference/media/advanced/prototype.md
Various fixes for kanban issues.
> Cw fixes 02

- package.json
> Deploy to production

- src/pages/uxp/index.md
- src/pages/uxp/known-issues.md
* Update with more known issues
* Address #94 (Image tags in dialogs) in the Known Issues section.
* Update main index page for UXP APIs to include the HTML & Spectrum sections.
> Update Known Issues (partially addresses #94 )

- src/pages/code_samples/react_samples/index.md
- src/pages/design/index.md
- src/pages/guides/debugging/index.md
- src/pages/guides/uxp_for_you/uxp_for_extendscript_devs/index.md
- src/pages/guides/uxp_guide/uxp-misc/file-access/index.md
- src/pages/guides/uxp_guide/uxp-misc/manifest-v4/index.md
- src/pages/guides/uxp_guide/uxp-toolchain/index.md
- src/pages/ps_reference/media/advanced/batchplay.md
> Cw fixes sprint2

- package.json
- reference-css.js
- reference-html.js
- reference-js.js
- reference-spectrum.js
> Fix sidebar #114

- package.json
> Deploy to stage (again)

- src/pages/ps_reference/classes/grouplayer.md
- src/pages/ps_reference/classes/layer.md
> Parenthesis needed in Nudge snippet #131

- package.json
> Sprint 3 to stage

- package.json
> Deploy 0.1.3 to prod

- package.json
New version of UDT; pushing to stage early to get it up
> [Out-of-sprint-deploy] Push to stage for UDT

- src/pages/code_samples/javascript_samples/index.md
> Add links for samples

- src/pages/design/ux-patterns/Designingforphotoshop.md
> Fix Spectrum 404s (#142)

- src/pages/distribution/packaging-your-plugin/index.md
> Fix bad link in packaging page

- package.json
> [Out-of-stage-deploy] Update UDT links

- src/pages/ps_reference/media/advanced/event-listener.md
> Fix eventNotifier 404

- package.json
> Stage for Sprint 4

- package.json
> Update theme & version

- package.json
> Push to prod

- src/pages/devtool/index.md
- src/pages/devtool/installation.md
Tweak installation from CCD wording for DevTools
> tweak wording

- package.json
> Push to stage

- package.json
> Deploy to prod

- src/pages/devtool/index.md
Update w/ system requirements for devtool
> System Requirements

- src/pages/guides/uxp_guide/uxp-misc/manifest-v5/index.md
> Doc fix: remove host comms section

- src/pages/guides/uxp_guide/uxp-misc/manifest-v5/index.md
> fix entrypoints updates

- src/pages/guides/distribution/index.md
- [ X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ X] I have read the **CONTRIBUTING** document.
> Links on this page were 404ing

- src/pages/guides/how-to/index.md
Fixes https://github.com/AdobeDocs/uxp-photoshop/issues/300
> Missing quote

- src/pages/guides/distribution/distribution-options/index.md
Fixed broken link to submission checklist
Fixes the 404
> Fixed link to submission checklist

- gatsby-config.js
readd path so the dropdown works again
will test in developer-stage
> readd year to path to fix selector

- src/pages/guides/uxp_guide/uxp-misc/manifest-v5/index.md
> update manifestv5 docs

- reference-ps.js
- src/pages/ps_reference/changelog/index.md
- src/pages/ps_reference/classes/document.md
- src/pages/ps_reference/classes/documents.md
- src/pages/ps_reference/classes/guide.md
- src/pages/ps_reference/classes/layer.md
- src/pages/ps_reference/classes/layers.md
- src/pages/ps_reference/classes/pathitems.md
- src/pages/ps_reference/classes/photoshop.md
- src/pages/ps_reference/colors/index.md
- src/pages/ps_reference/known-issues/index.md
- src/pages/ps_reference/media/batchplay.md
- src/pages/ps_reference/media/photoshopaction.md
- src/pages/ps_reference/media/photoshopcore.md
- src/pages/ps_reference/media/uxpscripting.md
- src/pages/ps_reference/modules/constants.md
- src/pages/ps_reference/objects/createoptions/layercreateoptions.md
This update fixes a number of small issues, but also adds:
-More layer filters (see Beta section in change log).
-Known Issues section.
> Photoshop UXP API documentation update

- reference-js.js
- src/pages/uxp/reference-js/Global Members/Crypto.md
- src/pages/uxp/reference-js/Global Members/Data Transfers/Blob.md
- src/pages/uxp/reference-js/Modules/uxp/Persistent File Storage/FileSystem.md
- src/pages/uxp/reference-js/Modules/uxp/Plugin Manager/Plugin.md
- src/pages/uxp/reference-js/Modules/uxp/Plugin Manager/PluginManager.md
- src/pages/uxp/reference-js/Modules/uxp/Plugin Manager/Script.md
- src/pages/uxp/reference-js/Modules/uxp/Plugin Manager/index.md
- yarn.lock
Changes for UXP API reference
UXP v6.3
> New changes for UXP v6.3

- src/pages/ps_reference/changelog/index.md
> Correction in uxp version

- package.json
- src/pages/ps_reference/changelog/index.md
- yarn.lock
> Updates to WebView documentation

- src/pages/guides/hybrid-plugins/faqs/index.md
- src/pages/guides/hybrid-plugins/getting-started/index.md
- src/pages/guides/hybrid-plugins/index.md
> Addressing review comments from Sam

- gatsby-config.js
> Fixed path for hybrid plugins

- yarn.lock
A fresh yarn lock to make CI happy.
> Ps Update yarn lock

- yarn.lock
Maybe this time it will be up-to-date enough.
> Ps yarn lock update

- .gitignore
- yarn.lock
> regen yarn.lock

- .github/workflows/github-pages.yml
- .gitignore
- yarn.lock
> GitHub pages yarn fix

- gatsby-config.js
- package.json
- src/pages/guides/uxp_guide/uxp-misc/index.md
- src/pages/guides/uxp_guide/uxp-misc/plugin-icons/index.md
- yarn.lock
> Plugin Icons

- src/pages/guides/hybrid-plugins/getting-started/index.md
- src/pages/guides/hybrid-plugins/index.md
- src/pages/ps_reference/changelog/index.md
- src/pages/ps_reference/classes/document.md
- src/pages/ps_reference/media/action-recording.md
- src/pages/ps_reference/media/imaging.md
- yarn.lock
We are adding a bit of description and some sample code to help developers get started using the Photoshop C++ SDK within the UXP plugin hybrid context.
We also fixed re-recording for UXP plugin Action steps.  However, there is some work that must be done to achieve that from the plugin's specified function.  See the documentation for more details.
> Ps docs update for hybrid and action re-recording

- src/pages/guides/hybrid-plugins/faqs/index.md
Update the hybrid faq page to point to the new instructions on Ps SDK access.
> Update FAQ page for hybrid + Ps sdk.

- package.json
- reference-js.js
- src/pages/guides/uxp_guide/uxp-misc/manifest-v5/index.md
- src/pages/ps_reference/changelog/index.md
- src/pages/uxp-api/changelog3P.md
- src/pages/uxp-api/reference-js/Global Members/Data Transfers/FormData.md
- src/pages/uxp-api/reference-js/Global Members/Data Transfers/Headers.md
- src/pages/uxp-api/reference-js/Global Members/Data Transfers/Request.md
- src/pages/uxp-api/reference-js/Global Members/Data Transfers/Response.md
- src/pages/uxp-api/reference-js/Global Members/HTML DOM/getComputedStyle.md
- src/pages/uxp-api/reference-js/Modules/uxp/Plugin Manager/index.md
- src/pages/uxp-api/reference-js/Modules/uxp/User Information/index.md
- src/pages/uxp-api/reference-js/Modules/uxp/XMP/getting-started/index.md
- src/pages/uxp-api/reference-js/Modules/uxp/XMP/index.md
- src/pages/uxp-api/versions3P.md
- yarn.lock
> UXP v7.3 updates

- src/pages/ps_reference/changelog/index.md
- src/pages/uxp-api/reference-js/Global Members/HTML DOM/getComputedStyle.md
> Fixing broken links

- package.json
- src/pages/index.md
- src/pages/uxp-api/reference-js/Global Members/HTML DOM/getComputedStyle.md
> Adding annual survey

- src/pages/uxp-api/reference-js/Global Members/HTML DOM/getComputedStyle.md
> correcting typo

- .yarnrc.yml
> fixing build error

- src/pages/index.md
> Updating survey text

- package.json
- src/pages/index.md
> Reverting survey

- package.json
- reference-css.js
- reference-spectrum.js
- src/pages/ps_reference/changelog/index.md
- src/pages/uxp-api/changelog3P.md
- src/pages/uxp-api/reference-css/Pseudo-classes/defined.md
- src/pages/uxp-api/reference-js/Global Members/HTML DOM/getComputedStyle.md
- src/pages/uxp-api/reference-js/Modules/uxp/XMP/getting-started/index.md
- src/pages/uxp-api/reference-spectrum/spectrum-widgets-to-swc-mapping/index.md
- src/pages/uxp-api/versions3P.md
- yarn.lock
> Changes for UXPv7.4

- reference-ps.js
- src/pages/ps_reference/changelog/index.md
- src/pages/ps_reference/classes/document.md
- src/pages/ps_reference/classes/layer.md
- src/pages/ps_reference/classes/layercomp.md
- src/pages/ps_reference/classes/photoshop.md
- src/pages/ps_reference/classes/selection.md
- src/pages/ps_reference/media/batchplay.md
- src/pages/ps_reference/media/displayunits.md
- src/pages/ps_reference/media/eventcodes.md
- src/pages/ps_reference/media/imaging.md
- src/pages/ps_reference/media/photoshopaction.md
- src/pages/ps_reference/media/photoshopcore.md
- src/pages/ps_reference/modules/constants.md
- src/pages/ps_reference/modules/types/generaltypes.md
- src/pages/ps_reference/modules/types/layertypes.md
- src/pages/ps_reference/objects/createoptions/textlayercreateoptions.md
- src/pages/ps_reference/objects/options/displayconfigurationoptions.md
- src/pages/ps_reference/objects/options/historystateinfo.md
- src/pages/ps_reference/objects/options/position.md
- src/pages/ps_reference/objects/returnobjects/cpuinfo.md
- src/pages/ps_reference/objects/returnobjects/dimensions.md
- src/pages/ps_reference/objects/returnobjects/displayconfiguration.md
- src/pages/ps_reference/objects/returnobjects/index.md
- src/pages/ps_reference/objects/returnobjects/simplebounds.md
Roughly a boatload of small changes, some new items, but mostly minor fixes.
See changelog for new items.
> Ps UXP DOM docs update May 2025

- src/pages/ps_reference/changelog/index.md
In the changelog:
Add UXP 8.4 Integration notes to 26.9 section.
Minor formatting changes for consistency.
> Changelog: UXP 8.4 Integration
